services:
  
  postgres:
    image: mavis-postgres:12.3
    container_name: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=client
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "client", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  client-server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: client-server:latest
    container_name: client-server
    volumes:
      - .:/app
    ports:
      - "1323:1323"
    command: make run
    depends_on:
      - postgres
    profiles:
      - server

  pgweb:
    container_name: pgweb
    restart: always
    image: cr-preview.pentium.network/sosedoff/pgweb:0.15.0
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - PGWEB_DATABASE_URL=postgres://admin:admin@postgres:5432/client?sslmode=disable
    depends_on:
      - postgres
    profiles:
      - server
volumes:
  dbdata:
